/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.resume.panel;

import com.company.dao.inter.EmploymentHistoryDaoInter;
import com.company.entity.EmploymentHistory;
import com.company.entity.User;
import com.company.main.Context;
import com.company.resume.config.Config;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class HistoryPanel extends javax.swing.JPanel {

    private EmploymentHistoryDaoInter history = Context.instanceEmploymentHistoryDao();

    private SimpleDateFormat sm = new SimpleDateFormat();
   

    /**
     * Creates new form HistoryPanel
     */
    public HistoryPanel() {
        Config.loggedInstory = history.getById(Config.loggedInUser.getId());
        initComponents();

    }

    public void fillComponents() {
        EmploymentHistory loggedInstory = Config.loggedInstory;
        txtAreaHeader.setText(loggedInstory.getHeader());
        txtAreaJobDescription.setText(loggedInstory.getJob_description());
        java.util.Date u = loggedInstory.getBegin_date();
        java.util.Date l = loggedInstory.getEnd_date();
        String begin = sm.format(u);
        String enddate = sm.format(l);
        txtbegindate.setText(begin);
        txtenddate.setText(enddate);

    }

    public void fillHistory(EmploymentHistory h) {
        try {
            String header = txtAreaHeader.getText();
            String begindate = txtbegindate.getText();
            String enddate = txtenddate.getText();
            String jobdescription = txtAreaJobDescription.getText();
            h.setHeader(header);
            java.util.Date du = sm.parse(begindate);
            long l = du.getTime();
            java.sql.Date sdate = new java.sql.Date(l);
            h.setBegin_date(sdate);
            java.util.Date d = sm.parse(enddate);
            long t = d.getTime();
            java.sql.Date ldate = new java.sql.Date(t);
            h.setEnd_date(ldate);
            h.setJob_description(jobdescription);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblheader = new javax.swing.JLabel();
        lbljobdescribtion = new javax.swing.JLabel();
        lblbegindate = new javax.swing.JLabel();
        lblenddate = new javax.swing.JLabel();
        txtbegindate = new javax.swing.JTextField();
        txtenddate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaJobDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaHeader = new javax.swing.JTextArea();
        btnsave = new javax.swing.JButton();

        lblheader.setText("Header");

        lbljobdescribtion.setText("JobDescription");

        lblbegindate.setText("begindate");

        lblenddate.setText("enddate");

        txtbegindate.setText("jTextField1");
        txtbegindate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbegindateActionPerformed(evt);
            }
        });

        txtenddate.setText("jTextField1");

        txtAreaJobDescription.setColumns(20);
        txtAreaJobDescription.setRows(5);
        jScrollPane1.setViewportView(txtAreaJobDescription);

        txtAreaHeader.setColumns(20);
        txtAreaHeader.setRows(5);
        jScrollPane2.setViewportView(txtAreaHeader);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblbegindate))
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtbegindate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblheader)
                            .addComponent(lbljobdescribtion)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblheader)
                            .addComponent(lblbegindate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbegindate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblenddate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lbljobdescribtion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbegindateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbegindateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbegindateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        try {
            String header = txtAreaHeader.getText();
            String begindate = txtbegindate.getText();
            String enddate = txtenddate.getText();
            String jobdescription = txtAreaJobDescription.getText();
            EmploymentHistory loggedInstory = Config.loggedInstory;
            loggedInstory.setHeader(header);
            java.util.Date du = sm.parse(begindate);
            long l = du.getTime();
            java.sql.Date sdate = new java.sql.Date(l);
            loggedInstory.setBegin_date(sdate);
            java.util.Date d = sm.parse(enddate);
            long t = d.getTime();
            java.sql.Date ldate = new java.sql.Date(t);
            loggedInstory.setEnd_date(ldate);
            loggedInstory.setJob_description(jobdescription);
            fillHistory(loggedInstory);
            System.out.println(loggedInstory.toString());
            history.updateHistory(loggedInstory);
            System.out.println(history.getById(10));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblbegindate;
    private javax.swing.JLabel lblenddate;
    private javax.swing.JLabel lblheader;
    private javax.swing.JLabel lbljobdescribtion;
    private javax.swing.JTextArea txtAreaHeader;
    private javax.swing.JTextArea txtAreaJobDescription;
    private javax.swing.JTextField txtbegindate;
    private javax.swing.JTextField txtenddate;
    // End of variables declaration//GEN-END:variables
}
